name: 'LTK Datadog Workflow Metrics'
description: 'DEPRECATED JANUARY 2022 IN FAVOR OF https://app.datadoghq.com/ci/pipelines'
runs:
  steps:
    - name: WARNING
      shell: bash
      run: echo "DEPRECATED JANUARY 2022 IN FAVOR OF https://app.datadoghq.com/ci/pipelines"
